apiVersion: v1
kind: Service
metadata:
  name: singiattend-services
  namespace: default
spec:
  selector:
    app: singiattend
  type: NodePort
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: singiattend-fe
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30000
  - name: singiattend-be
    protocol: TCP
    port: 62812
    targetPort: 62812
    nodePort: 30001
  - name: singiattend-db
    protocol: TCP
    port: 27017
    targetPort: 27017
    nodePort: 30002 