package dev.markodojkic.singiattend.server.entity;

import javax.persistence.*;

@Entity
@Table(name = "faculty")
public class Faculty {
    @Id
    @Column(name = "faculty_id")
    @GeneratedValue(strategy = GenerationType.IDENTITY) //Generated by sql database AUTO_INCREMENT
    private int id;
    @Column(name = "title")
    private String title;
    @Column(name = "title_english")
    private String title_english;

    public Faculty() { }

    public Faculty(int id, String title, String title_english) {
        this.id = id;
        this.title = title;
        this.title_english = title_english;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getTitleEnglish() {
        return title_english;
    }

    public void setTitleEnglish(String title_english) {
        this.title_english = title_english;
    }
}
