package dev.markodojkic.singiattend.server.entity;

import javax.persistence.*;
import java.sql.Time;

@Entity
@Table(name = "lecture")
public class Lecture {
    @Id
    @Column(name = "lecture_id")
    @GeneratedValue(strategy = GenerationType.IDENTITY) //Generated by sql database AUTO_INCREMENT
    private int id;
    @Column(name = "log_file_name")
    private String log_file_name;
    @Column(name = "start_time")
    private Time start_time;
    @Column(name = "end_time")
    private Time end_time;

    public Lecture() { }

    public Lecture(int id, String log_file_name, Time start_time, Time end_time) {
        this.id = id;
        this.log_file_name = log_file_name;
        this.start_time = start_time;
        this.end_time = end_time;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getLog_file_name() {
        return log_file_name;
    }

    public void setLog_file_name(String log_file_name) {
        this.log_file_name = log_file_name;
    }

    public Time getStart_time() {
        return start_time;
    }

    public void setStart_time(Time start_time) {
        this.start_time = start_time;
    }

    public Time getEnd_time() {
        return end_time;
    }

    public void setEnd_time(Time end_time) {
        this.end_time = end_time;
    }
}