package dev.markodojkic.singiattend.server.entity;

import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.*;
import java.sql.Date;

@Entity
@Table(name = "subject")
public class Subject {
    @Id
    @Column(name = "subject_id")
    @GeneratedValue(strategy = GenerationType.IDENTITY) //Generated by sql database AUTO_INCREMENT
    private int id;
    @Column(name = "title")
    private String title;
    @Column(name = "title_english")
    private String title_english;
    @Column(name = "professor_id")
    private int professorId;
    @Column(name = "assistant_id")
    private int assistantId;
    @Column(name = "last_lecture_at")
    private String lastLectureAt;
    @Column(name = "is_inactive")
    private boolean isInactive;

    public Subject() { }

    public Subject(int id, String title, String title_english, int professorId, int assistantId, String lastLectureAt, boolean isInactive) {
        this.id = id;
        this.title = title;
        this.title_english = title_english;
        this.professorId = professorId;
        this.assistantId = assistantId;
        this.lastLectureAt = lastLectureAt;
        this.isInactive = isInactive;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getTitleEnglish() {
        return title_english;
    }

    public void setTitleEnglish(String title_english) {
        this.title_english = title_english;
    }

    public int getProfessorId() {
        return professorId;
    }

    public void setProfessorId(int professorId) {
        this.professorId = professorId;
    }

    public int getAssistantId() {
        return assistantId;
    }

    public void setAssistantId(int assistantId) {
        this.assistantId = assistantId;
    }

    public String getLastLectureAt() {
        return lastLectureAt;
    }

    public void setLastLectureAt(String lastLectureAt) {
        this.lastLectureAt = lastLectureAt;
    }

    public boolean isInactive() {
        return isInactive;
    }

    public void setInactive(boolean inactive) {
        isInactive = inactive;
    }
}