server:
  port: ${PORT:62810}
management:
  endpoints:
    web:
      exposure:
        include: "gateway"
  endpoint:
    gateway:
      enabled: true
multitenancy:
  multitenantJSON: ${TENANTS_JSON}