apiVersion: v1
kind: ConfigMap
metadata:
  name: singiattend-proxy-cm
data:
  PORT: '62810'
  TENANTS_JSON: |
    [
      {"headerIdentification": "SingidunumBG", "uri": "http://singiattend-bg-service.default.svc.cluster.local:62813"},
      {"headerIdentification": "SingidunumNS", "uri": "http://singiattend-ns-service.default.svc.cluster.local:62814"},
      {"headerIdentification": "SingidunumNIS", "uri": "http://singiattend-nis-service.default.svc.cluster.local:62815"}
    ]