apiVersion: apps/v1
kind: Deployment
metadata:
  name:  singiattend-fe-mongo-proxy
  namespace: default
  labels:
    app: singiattend-fe-mongo-proxy
spec:
  selector:
    matchLabels:
      app: singiattend-fe-mongo-proxy
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:singiattend-fe-mongo-proxy
    spec:
      containers:
        - name: singiattend-fe-mongo-proxy
          image: madojkic/main:singiattend-fe-mongo-proxy-v2.5.0
          ports:
            - name: singiattend-fe
              containerPort: 8080
              protocol: TCP
            - name: singiattend-db
              containerPort: 27017
              protocol: TCP
            - name: singiattend-gw
              containerPort: 62810
              protocol: TCP
          envFrom:
            - configMapRef:
                name: singiattend-proxy-cm
          resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: '1'
              memory: 2Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      imagePullSecrets:
        - name: madojkic-credential