apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:                  # For local development only; use proper storage class in production
    path: /mnt/data/mongodb
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  singiattend-mongo
  namespace: default
  labels:
    app: singiattend-mongo
spec:
  selector:
    matchLabels:
      app: singiattend-mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: singiattend-mongo
    spec:
      containers:
        - name: singiattend-mongo
          image: madojkic/main:singiattend-mongo-v2.5.0
          ports:
            - name: singiattend-db
              containerPort: 27017
              protocol: TCP
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: '1'
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      volumes:
      - name: mongodb-storage
        persistentVolumeClaim:
          claimName: mongodb-pvc
      restartPolicy: Always
      imagePullSecrets:
        - name: madojkic-credential