package dev.markodojkic.singiattend.server.entity;

import javax.persistence.*;

@Entity
@Table(name = "student")
public class Student {
    @Id
    @Column(name = "student_id")
    @GeneratedValue(strategy = GenerationType.IDENTITY) //Generated by sql database AUTO_INCREMENT
    private int id;
    @Column(name = "name_surname")
    private String name_surname;
    @Column(name = "index")
    private String index;
    @Column(name = "password_hash")
    private String password_hash;
    @Column(name = "email")
    private String email;
    @Column(name = "study_id")
    private int studyId;
    @Column(name = "year")
    private String year; //Enum: '1','2','3','4','5'

    public Student() { }

    public Student(int id, String name_surname, String index, String password_hash, String email, int studyId, String year) {
        this.id = id;
        this.name_surname = name_surname;
        this.index = index;
        this.password_hash = password_hash;
        this.email = email;
        this.studyId = studyId;
        this.year = year;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName_surname() {
        return name_surname;
    }

    public void setName_surname(String name_surname) {
        this.name_surname = name_surname;
    }

    public String getIndex() {
        return index;
    }

    public void setIndex(String index) {
        this.index = index;
    }

    public String getPassword_hash() {
        return password_hash;
    }

    public void setPassword_hash(String password_hash) {
        this.password_hash = password_hash;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public int getStudyId() {
        return studyId;
    }

    public void setStudyId(int studyId) {
        this.studyId = studyId;
    }

    public String getYear() {
        return year;
    }

    public void setYear(String year) {
        this.year = year;
    }
}
