package dev.markodojkic.singiattend.server.entity;

import javax.persistence.*;

@Entity
@Table(name = "study")
public class Study {
    @Id
    @Column(name = "study_id")
    @GeneratedValue(strategy = GenerationType.IDENTITY) //Generated by sql database AUTO_INCREMENT
    private int id;
    @Column(name = "title")
    private String title;
    @Column(name = "title_english")
    private String title_english;
    @Column(name = "faculty_id")
    private int facultyId;
    @Column(name = "taught_in")
    private String taught_in; //Enum: 'engleski','srpski'

    public Study() { }

    public Study(int id, String title, String title_english, int facultyId, String taught_in) {
        this.id = id;
        this.title = title;
        this.title_english = title_english;
        this.facultyId = facultyId;
        this.taught_in = taught_in;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getTitleEnglish() {
        return title_english;
    }

    public void setTitleEnglish(String title_english) {
        this.title_english = title_english;
    }

    public int getFacultyId() {
        return facultyId;
    }

    public void setFacultyId(int facultyId) {
        this.facultyId = facultyId;
    }

    public String getTaught_in() {
        return taught_in;
    }

    public void setTaught_in(String taught_in) {
        this.taught_in = taught_in;
    }
}
