package dev.markodojkic.singiattend.server.entity;

import javax.persistence.*;

@Entity
@Table(name = "subject_study")
public class Subject_Study {
    @Id
    @Column(name = "subject_study")
    @GeneratedValue(strategy = GenerationType.IDENTITY) //Generated by sql database AUTO_INCREMENT
    private int id;
    @Column(name = "subject_id")
    private int subjectId;
    @Column(name = "study_id")
    private int studyId;
    @Column(name = "year")
    private int year; //Enum: 1, 2, 3, 4

    public Subject_Study() { }

    public Subject_Study(int subjectId, int studyId, int year) {
        this.subjectId = subjectId;
        this.studyId = studyId;
        this.year = year;
    }

    public int getSubjectId() {
        return subjectId;
    }

    public void setSubjectId(int subjectId) {
        this.subjectId = subjectId;
    }

    public int getStudyId() {
        return studyId;
    }

    public void setStudyId(int studyId) {
        this.studyId = studyId;
    }

    public int getYear() {
        return year;
    }

    public void setYear(int year) {
        this.year = year;
    }
}
